/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface IClearinghouseEventEmitterInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "ClearinghouseInitialized"
      | "Liquidation"
      | "ModifyCollateral"
  ): EventFragment;
}

export namespace ClearinghouseInitializedEvent {
  export type InputTuple = [
    endpoint: AddressLike,
    quote: AddressLike,
    fees: AddressLike
  ];
  export type OutputTuple = [endpoint: string, quote: string, fees: string];
  export interface OutputObject {
    endpoint: string;
    quote: string;
    fees: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationEvent {
  export type InputTuple = [
    liquidatorSubaccount: BytesLike,
    liquidateeSubaccount: BytesLike,
    mode: BigNumberish,
    healthGroup: BigNumberish,
    amount: BigNumberish,
    amountQuote: BigNumberish,
    insuranceCover: BigNumberish
  ];
  export type OutputTuple = [
    liquidatorSubaccount: string,
    liquidateeSubaccount: string,
    mode: bigint,
    healthGroup: bigint,
    amount: bigint,
    amountQuote: bigint,
    insuranceCover: bigint
  ];
  export interface OutputObject {
    liquidatorSubaccount: string;
    liquidateeSubaccount: string;
    mode: bigint;
    healthGroup: bigint;
    amount: bigint;
    amountQuote: bigint;
    insuranceCover: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModifyCollateralEvent {
  export type InputTuple = [
    amount: BigNumberish,
    subaccount: BytesLike,
    productId: BigNumberish
  ];
  export type OutputTuple = [
    amount: bigint,
    subaccount: string,
    productId: bigint
  ];
  export interface OutputObject {
    amount: bigint;
    subaccount: string;
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IClearinghouseEventEmitter extends BaseContract {
  connect(runner?: ContractRunner | null): IClearinghouseEventEmitter;
  waitForDeployment(): Promise<this>;

  interface: IClearinghouseEventEmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ClearinghouseInitialized"
  ): TypedContractEvent<
    ClearinghouseInitializedEvent.InputTuple,
    ClearinghouseInitializedEvent.OutputTuple,
    ClearinghouseInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidation"
  ): TypedContractEvent<
    LiquidationEvent.InputTuple,
    LiquidationEvent.OutputTuple,
    LiquidationEvent.OutputObject
  >;
  getEvent(
    key: "ModifyCollateral"
  ): TypedContractEvent<
    ModifyCollateralEvent.InputTuple,
    ModifyCollateralEvent.OutputTuple,
    ModifyCollateralEvent.OutputObject
  >;

  filters: {
    "ClearinghouseInitialized(address,address,address)": TypedContractEvent<
      ClearinghouseInitializedEvent.InputTuple,
      ClearinghouseInitializedEvent.OutputTuple,
      ClearinghouseInitializedEvent.OutputObject
    >;
    ClearinghouseInitialized: TypedContractEvent<
      ClearinghouseInitializedEvent.InputTuple,
      ClearinghouseInitializedEvent.OutputTuple,
      ClearinghouseInitializedEvent.OutputObject
    >;

    "Liquidation(bytes32,bytes32,uint8,uint32,int128,int128,int128)": TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;
    Liquidation: TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;

    "ModifyCollateral(int128,bytes32,uint32)": TypedContractEvent<
      ModifyCollateralEvent.InputTuple,
      ModifyCollateralEvent.OutputTuple,
      ModifyCollateralEvent.OutputObject
    >;
    ModifyCollateral: TypedContractEvent<
      ModifyCollateralEvent.InputTuple,
      ModifyCollateralEvent.OutputTuple,
      ModifyCollateralEvent.OutputObject
    >;
  };
}
