/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Endpoint__factory } from "./Endpoint__factory";
export { ISanctionsList__factory } from "./ISanctionsList__factory";
