/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ClearinghouseStorage,
  ClearinghouseStorageInterface,
} from "../../contracts/ClearinghouseStorage";

const _abi = [
  {
    inputs: [],
    name: "insurance",
    outputs: [
      {
        internalType: "int128",
        name: "",
        type: "int128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ClearinghouseStorage__factory {
  static readonly abi = _abi;
  static createInterface(): ClearinghouseStorageInterface {
    return new Interface(_abi) as ClearinghouseStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ClearinghouseStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ClearinghouseStorage;
  }
}
