/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFEndpoint,
  IFEndpointInterface,
} from "../../../contracts/interfaces/IFEndpoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "productId",
        type: "uint32",
      },
      {
        internalType: "int128",
        name: "priceX18",
        type: "int128",
      },
    ],
    name: "setPriceX18",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFEndpoint__factory {
  static readonly abi = _abi;
  static createInterface(): IFEndpointInterface {
    return new Interface(_abi) as IFEndpointInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFEndpoint {
    return new Contract(address, _abi, runner) as unknown as IFEndpoint;
  }
}
