/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVersion,
  IVersionInterface,
} from "../../../contracts/interfaces/IVersion";

const _abi = [
  {
    inputs: [],
    name: "getVersion",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVersion__factory {
  static readonly abi = _abi;
  static createInterface(): IVersionInterface {
    return new Interface(_abi) as IVersionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVersion {
    return new Contract(address, _abi, runner) as unknown as IVersion;
  }
}
