/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClearinghouseEventEmitter,
  IClearinghouseEventEmitterInterface,
} from "../../../../contracts/interfaces/clearinghouse/IClearinghouseEventEmitter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "endpoint",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "quote",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "fees",
        type: "address",
      },
    ],
    name: "ClearinghouseInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "liquidatorSubaccount",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "liquidateeSubaccount",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint8",
        name: "mode",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "healthGroup",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "int128",
        name: "amount",
        type: "int128",
      },
      {
        indexed: false,
        internalType: "int128",
        name: "amountQuote",
        type: "int128",
      },
      {
        indexed: false,
        internalType: "int128",
        name: "insuranceCover",
        type: "int128",
      },
    ],
    name: "Liquidation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int128",
        name: "amount",
        type: "int128",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "subaccount",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "productId",
        type: "uint32",
      },
    ],
    name: "ModifyCollateral",
    type: "event",
  },
] as const;

export class IClearinghouseEventEmitter__factory {
  static readonly abi = _abi;
  static createInterface(): IClearinghouseEventEmitterInterface {
    return new Interface(_abi) as IClearinghouseEventEmitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClearinghouseEventEmitter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IClearinghouseEventEmitter;
  }
}
